Use default-construct-and-assign for certain variables
This fixes a compiler warning in gcc 8+. That compiler now warns when
calling memset writes to private variables in a struct. This appears
to mostly be the cause of the warnings here. From
https://gcc.gnu.org/gcc-8/changes.html:

-Wclass-memaccess warns when objects of non-trivial class types are
manipulated in potentially unsafe ways by raw memory functions such as
memcpy, or realloc. … The warning also detects calls that would bypass
access controls to data members.

Example of specific diagnostic message:

WeaveExchangeMgr.cpp:557:50: error: ‘void* memset(void*, int, size_t)’
clearing an object of type ‘class nl::Weave::ExchangeContext’ with no
trivial copy-assignment; use assignment or value-initialization
instead [-Werror=class-memaccess]

             memset(ec, 0, sizeof(ExchangeContext));
                                                  ^