Use libc++ as default Android STL when make Makefile-Android
-- Internal android weave daily build fails in
src/lib/../../src/device-manager/WeaveDataManagementClient.cpp:39:18:
fatal error: string: No such file or directory
  #include <string>
-- At default, it uses system, but it don't have c++ string,
/usr/local/android/android-ndk-r14/system/include.
-- if using libc++, it has
/usr/local/android/android-ndk-r14/sources/cxx-stl/llvm-libc++/include/string.
-- Therefore, use Android NDK C++ runtime to build against libc++
-- checking latest android ndk, the same applies.